use_frameworks!

target 'GINetworking_Example' do
    
  pod 'GINetworking', :path => '../'

  pod 'XKit', :path => '../../XKit'
  
  target 'GINetworking_Tests' do
    inherit! :search_paths

    
  end
end
