use_frameworks!

target 'GINetworking_Example' do
    
  pod 'Anvil', :path => '../'

  pod 'XKit', :git => 'git@114.242.31.175:wangzhichen/iOS_X.git'
  
  target 'GINetworking_Tests' do
    inherit! :search_paths

    
  end
end
